# Generated by Django 2.1.15 on 2020-04-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200410_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_start_time', models.TimeField()),
                ('leave_end_time', models.TimeField()),
                ('leave_reason', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'WAITING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='waiting', max_length=30)),
                ('days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=255)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_start_time', models.TimeField()),
                ('leave_end_time', models.TimeField()),
                ('leave_reason', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'WAITING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='waiting', max_length=30)),
                ('days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
